version: "2"

formatters:
  enable:
    - gofumpt
    - golines
    - gci

  settings:
    gofumpt:
      extra-rules: true

    golines:
      max-len: 90
      tab-len: 4
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true
