services:
  notes:
    depends_on:
      - db
    build:
      target: prod
    container_name: notes
  
  test:
    build:
      target: test

  # call like `docker compose run --rm migrate up/down/force/...`
  migrate:
    image:
      migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint:
      - migrate
      - "-path=/migrations/"
      - "-database=postgres://${POSTGRES__USER}:${POSTGRES__PASSWORD}@db/${POSTGRES__DB}?sslmode=disable"

  db:
    image: postgres:19beta3-alpine3.24
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DB}
    volumes:
      - pgdata:/var/lib/postgresql/19/docker
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d ${POSTGRES__DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  pgdata:
